### DISCUSSION TITLE
Problem to conda-build SOFA

### DISCUSSION THREAD

**Discussion by Namejess** [sofa-framework/sofa#3638] [Build / Config / Environment] [answered]
Hi everyone ! ✌

I try to create a conda package via conda-build in order to be able to deliver SOFA ready, directly uploaded on Anaconda.org

Windows 10.

I have created a recipe folder with a meta.yaml file that looks like this (in sofa/src/ from git clone):

```yaml

package:
  name: sofa
  version: 22.11.00

source:
  path: ..
  

requirements:
  build:
    - {{ compiler('cxx') }}
    - "cmake"
    - setuptools
    - "boost >=1.65.1"
    - "python >=3.7"
    - "qt >=5.12.9"
    - "Scipy >=1.2.0"
    - "numpy >=1.16.0"
    - "pybind11"

  run:
    - "eigen >=3.2.10"
    - "qt >=5.12.9"
    - "qt-webengine >=5.15"
    - qt-main >=5.15
    - python
    - "boost >=1.65.1"
    

build:
  number: 0
  script: |
    cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH:PATH="C:/Qt/5.15.2/msvc2019_64" -DCMAKE_PREFIX_PATH:PATH="C:/CDA CCI/INRIA/sofa/src/Eigen3" 

about:
  home: https://github.com/sofa-framework/sofa
  license: MIT
  license_file: LICENSE
```

---------------

The build comes to the end but my error log looks like this (sorry for the length):

```log
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: C:/ProgramData/Anaconda3/conda-bld/sofa_1675956123461/work/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_6f43e.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:m && MSBuild version 17.4.0+18d5aef85 for .NET Framework

  Compilateur d'optimisation Microsoft (R) C/C++ version 19.34.31935 pour x64

  src.c

C:\ProgramData\Anaconda3\conda-bld\sofa_1675956123461\work\build\CMakeFiles\CMakeTmp\src.c(15,3): warning C4013: 'pthread_atfork' non défini(e) ; extern retournant int pris par défaut [C:\ProgramData\Anaconda3\conda-bld\sofa_1675956123461\work\build\CMakeFiles\CMakeTmp\cmTC_6f43e.vcxproj]

  Copyright (C) Microsoft Corporation. Tous droits réservés.

  cl /c /I"C:\vcpkg\installed\x64-windows\include" /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D CMAKE_HAVE_LIBC_PTHREAD /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_6f43e.dir\Debug\\" /Fd"cmTC_6f43e.dir\Debug\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\ProgramData\Anaconda3\conda-bld\sofa_1675956123461\work\build\CMakeFiles\CMakeTmp\src.c"

src.obj : error LNK2019: symbole externe non résolu pthread_atfork référencé dans la fonction main [C:\ProgramData\Anaconda3\conda-bld\sofa_1675956123461\work\build\CMakeFiles\CMakeTmp\cmTC_6f43e.vcxproj]

C:\ProgramData\Anaconda3\conda-bld\sofa_1675956123461\work\build\CMakeFiles\CMakeTmp\Debug\cmTC_6f43e.exe : fatal error LNK1120: 1 externes non résolus [C:\ProgramData\Anaconda3\conda-bld\sofa_1675956123461\work\build\CMakeFiles\CMakeTmp\cmTC_6f43e.vcxproj]



Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}
```

--------------------

Does anyone have an idea for debugging?

Thanks 🤞
