### DISCUSSION TITLE
Compilation failed (conda-build / Ninja)

### DISCUSSION THREAD

**Discussion by Namejess** [sofa-framework/sofa#3645] [Build / Config / Environment]
Hello everyone ! 

My compilation fails at around 558/1970 (ninja build). This is logs : 

![image](https://user-images.githubusercontent.com/40612124/218431177-aeea0f22-945c-4fa5-823c-ed14d11f7930.png)

![image](https://user-images.githubusercontent.com/40612124/218431214-991e3589-482f-4ca8-b0e8-4ee03a7dc320.png)

My meta.yaml for the conda-build : 

```yaml
package:
  name: sofa
  version: 22.11.00

source:
  path: ..
  

requirements:
  build:
    - {{ compiler('cxx') }}
    - "cmake"
    - "ninja"
    - setuptools
    - "boost >=1.65.1"
    - "python >=3.7"
    - "qt >=5.12.9"
    - "Scipy >=1.2.0"
    - "numpy >=1.16.0"
    - "pybind11"
    - boost-cpp>=1.67

  run:
    - "ninja"    
    - "cmake"
    - "eigen >=3.2.10"
    - "qt >=5.12.9"
    - "qt-webengine >=5.15"
    - qt-main >=5.15
    - "python >=3.7"
    - "boost >=1.65.1"
    - boost-cpp>=1.67

  host:
    - "boost-cpp>=1.67"
    - "boost >=1.65.1"


build:
  number: 0
  rpaths:
    - lib/
    - lib/R/lib/
  script: |
    cmake -S . -B build \
    -DCMAKE_GENERATOR=Ninja \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DCMAKE_PREFIX_PATH:PATH="C:/Qt/5.15.2/msvc2019_64" \ 
    -DCMAKE_PREFIX_PATH:PATH="C:/CDA CCI/INRIA/sofa/src/Eigen3" \
    -DCMAKE_PREFIX_PATH:PATH="C:/CDA CCI/INRIA/sofa2/sofa/src/SOFA_WinDepPack_20210304" \
    -DPLUGIN_SOFAPYTHON3=ON \
    -DPLUGIN_SOFAMATRIX=ON 
    
    cd $SRC_DIR/build 
    ninja

about:
  home: https://github.com/sofa-framework/sofa
  license: MIT
  license_file: LICENSE

extra:
  channels:
    - conda-forge
    - defaults
```

Precision : Just before the ninja launch, there is a warning : 

![image](https://user-images.githubusercontent.com/40612124/218431737-9ae46021-d14b-44b0-8be3-1f631a691d5e.png)

If anyone has an idea :)
