### DISCUSSION TITLE
Create a functionnal package of SOFA Framework to a Conda environnement

### DISCUSSION THREAD

**Discussion by Namejess** [sofa-framework/sofa#3661] [Develop in C++]
# Create a functionnal package of SOFA Framework to a Conda environnement

- Overview & objectives
- Solutions & tools
- PoC

## Overview

@hugtalbot  gave me a mission : I have 2 weeks to purpose a PoC of a Sofa packaging to a Conda environment.

There are some difficulties for some people to implement Sofa in a Python ecosystem (Anaconda) and there is no functionnal package at the moment. My goal is to determine what it is possible to achieve, to understand the needs of the end-users, and with which tools.

## Solutions & tools

After some discussions, there are several tools that can be used to make the packaging :

- [Pypi](https://duckduckgo.com)
- [Conda Forge / Build](https://duckduckgo.com)

Some differences against thses two tools :

### Pypi

Pip is a package manager to install python packages from Pypi. Generally, you download **source code** that is installed according to instructions in _setup.py_, using setuptools.

Most appropriate for pure Python packages, and Pip depends on a python interpreter.

### Conda

Packages are downloaded from [Anaconda Cloud](https://duckduckgo.com). With conda, we download and install a **pre-compiled platform dependent binaries**. Conda is a package manager that handles not only Python packages but also packages in other languages, and can create **virtual environments**, that do not need to contain Python.

In this case, Conda seems to be more appropriate, because of pre-compilated environments.

## PoC

Here all ressources i used to build the solution :

- [Conda Build Documentation](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html)
- [Anaconda.org](https://anaconda.org/namejess/conda_gc_test)
- [Anaconda Documentation](https://docs.anaconda.com/anaconda/install/linux/)
- [SOFA Documentation](https://www.sofa-framework.org/community/doc/getting-started/build/windows/)
- [Conda Forge Documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html#using-cmake)
- [Stack Overflow Thread](https://stackoverflow.com/questions/69185315/how-to-install-c-program-into-conda-environment-from-source)

At first I was on a Windows system but after several builds attempts (which I will come back to) I decided to go on an Archlinux system, which solved many of my problems.

To create a Conda package, you have to install the whole [Anaconda](https://docs.anaconda.com/anaconda/install/linux/) ecosystem. To use GUI packages with Linux, you will need to install the following extended dependencies for Qt:

Arch :

```shell
sudo pacman -Sy libxau libxi libxss libxtst libxcursor libxcomposite libxdamage libxfixes libxrandr libxrender mesa-libgl  alsa-lib libglvnd
```

Debian / Ubuntu :

```shell
sudo apt-get install libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6
```
Download and launch the [.sh](https://www.anaconda.com/products/distribution#linux) installation (follow the [Installation Guide](https://docs.anaconda.com/anaconda/install/linux/) if got a problem).

Then, install [conda build](https://docs.conda.io/projects/conda-build/en/latest/install-conda-build.html) : 

```shell
conda install conda-build
```

To [Build a conda package from scratch](https://docs.conda.io/projects/conda-build/en/stable/user-guide/tutorials/build-pkgs.html) you have to create a file a root directory named `meta.yaml`. It is with this file that all the configuration of the package is done. Setup a directory like this :

```shell
git clone -b v22.12 https://github.com/sofa-framework/sofa.git sofa/src
```

![Tree](images/20230214100807.png)

Create a folder that will contain the `meta.yaml` file (_recipe_ is a good practice name) :

```shell
mkdir recipe
cd recipe/
touch meta.yaml
```

The template by default looks like this :

```yaml
package:
  name:
  version:

source:
  git_rev:
  git_url:

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home:
```

Here is the meta.yaml file I used after long trials and iterations (with commentary):

```yaml
package:
  name: sofa
  version: 22.11.00

source:
  path : ..
requirements:
  build:
    - {{ compiler('cxx') }}
    - "cmake"
    - "ninja"
    - "clang"
    - setuptools
    - "boost >=1.65.1"
    - "python >=3.9"

  host:
    - "boost-cpp>=1.67"
    - "boost >=1.65.1"

build:
  number: 0

  script: |
    cmake -S . -B build \
    -DCMAKE_GENERATOR=Ninja \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_C_COMPILER=clang \

    cd $SRC_DIR/build 
    ninja

about:
  home: https://github.com/sofa-framework/sofa
  license: MIT
  license_file: LICENSE

extra:
  channels:
    - conda-forge
    - defaults

```

To launch build :

```shell
sudo conda build .
```

## Errors

If you get this far, normally the build will break around 860/1970, with this error : 

![image](https://user-images.githubusercontent.com/40612124/219688549-65eacdfc-2588-4ac2-94bc-ad52681ea741.png)

## Possible Solutions

We tried to skip the script in meta.yaml and create a file named build.sh (in the same folder *recipe*). This script looks like this : 

```bash
#!/bin/bash

  

# Define the path to the directory where the script will be created

SCRIPT_PATH="$CONDA_PREFIX/include/sofa/plugins/CMakeLists.txt"

  

# Define the content of the script

SCRIPT_CONTENT='cmake_minimum_required(VERSION 3.22)

  

# REQUIRED DEPENDENCIES

set(SOFA_BUILD_METIS "ON" CACHE BOOL "" FORCE)

set(PLUGIN_SOFAPYTHON "OFF" CACHE BOOL "" FORCE)

set(PLUGIN_SOFAPYTHON3 "ON" CACHE BOOL "" FORCE)

  

#EXTERNAL DIRECTORY'"'"'s plugins

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake")

find_package(SofaFramework REQUIRED)

sofa_add_plugins(STLIB SoftRobots ModelOrderReduction SofaPython3 BeamAdapter CosseratPlugin SoftRobotsInverse)

  

set(PLUGIN_MPC_PLUGIN "OFF" CACHE BOOL "" FORCE)

set(PLUGIN_STLIB "ON" CACHE BOOL "" FORCE)

set(PLUGIN_SOFTROBOTS "ON" CACHE BOOL "" FORCE)

set(PLUGIN_SOFTROBOTSINVERSE "ON" CACHE BOOL "" FORCE)

set(PLUGIN_COSSERATPLUGIN "ON" CACHE BOOL "" FORCE)

set(PLUGIN_BEAMADAPTER "ON" CACHE BOOL "" FORCE)

set(PLUGIN_MODELORDERREDUCTION "ON" CACHE BOOL "" FORCE)

set(PLUGIN_SOFAOFFSCREENCAMERA "OFF" CACHE BOOL "" FORCE)

'

# Create the script

mkdir -p "$CONDA_PREFIX/include/sofa/plugins/"

echo "$SCRIPT_CONTENT" > "$SCRIPT_PATH"

  

# Build SOFA

  

cmake -S $CONDA_PREFIX/include/sofa/plugins/ -B build \

-DCMAKE_GENERATOR=Ninja \

-DCMAKE_INSTALL_PREFIX="$PREFIX" \

-DCMAKE_CXX_COMPILER=clang++ \

-DCMAKE_C_COMPILER=clang \

-DPLUGIN_SOFAMATRIX=ON

  

cd $SCRIPT_PATH

ninja
```

We **need** you ! If you have any ideas, do not hesitate :+1:

**Comment by alxbilger** [comment]
Thanks for sharing your experiments

**Comment by EtienneMenager** [comment]
Hi guys,

I also did some testing on the packaging via conda. This would allow to have the runSofa and the python interface directly accessible for users (for developers it is necessary to have access to the source code). I managed to get a version of runSofa to run, even though I'm currently having problems with Qt. Here is my configuration: 

```
package:
  name: sofa
  version: 22.11.00

source:
  - git_url: https://github.com/sofa-framework/sofa.git
    folder: ./sofa/sofa/src
    git_tag: v22.12.00

requirements:
  build:
    - {{compiler('cxx')}}
    - python>=3.9
    - boost-cpp>=1.67
    - cmake
    - ninja
    - clang
    - setuptools
    - boost>=1.65.1
    - python>=3.7
    - qt>=5.12.9
    - Scipy>=1.2.0
    - numpy>=1.16.0
    - pybind11

  run:
    - python>=3.9
    - eigen>=3.2.10
    - qt>=5.12.9
    - qt-webengine>=5.15
    - qt-main>=5.15
    - python>=3.7
    - boost>=1.65.1
    - boost-cpp>=1.67

build:
  number: 0
  binary_relocation: false

about:
  home: https://github.com/sofa-framework/sofa
  license: MIT
  license_file: LICENSE.LGPL.txt

extra:
  channels:
    - conda-forge
    - defaults

```

and my build: 

```
#!/bin/bash
CONDA_OVERRIDE_OSX=11.5.1
CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"

mkdir ./sofa/sofa/build
cmake -S ./sofa/sofa/src -B ./sofa/sofa/build \
  -DCMAKE_GENERATOR=Ninja \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DCMAKE_C_COMPILER=clang \
  -DPLUGIN_SOFAMATRIX=ON

cd ./sofa/sofa/build
ninja -j4
#ninja install

```

To improve the installation it would be necessary to do: 
1. Fix the path to Qt.
2. Integrate the plugins and in particular SofaPython3.
3. Organize the elements at installation time (for the moment it is stored anywhere in the PREFIX_PATH).
4. Adapt the installation for cross platform. 

Cheers, 

Etienne
