### DISCUSSION TITLE
Update versions of actions/download-artifact and actions/upload-artifact

### DISCUSSION THREAD

**Discussion by alxbilger** [sofa-framework/sofa#4979] [Build / Config / Environment]
It concerns SOFA plugins relying on GitHub actions.

> actions/download-artifact@v3 is scheduled for deprecation on November 30, 2024. Similarly, v1/v2 are scheduled for deprecation on June 30, 2024. Please update your workflow to use v4 of the artifact actions.

> actions/upload-artifact@v3 is scheduled for deprecation on November 30, 2024. Similarly, v1/v2 are scheduled for deprecation on June 30, 2024. Please update your workflow to use v4 of the artifact actions.

Both actions are massively used in SOFA plugins. Most of them still use the v2. They need to be upgraded

In some SOFA plugins, GitHub has used a bot to upgrade `actions/download-artifact`. Unfortunately, it's only half of the job. `actions/upload-artifact` must be upgraded too. There is even an incompatibility between `actions/upload-artifact@v2` and `actions/download-artifact@v4.1.7` (the version suggested by the bot). This incompatibility make the build failing.

Unfortunately, the new versions of the actions have new rules: some characters are forbidden in the name of the artifact to avoid cross-platform problems. That is why the name of the artifact must be sanitized first.

Here are the changes I recommend:

1. Upgrade the version of `actions/download-artifact` from v2 to v4.1.7

```diff
      - name: Install artifact
-        uses: actions/download-artifact@v2
+        uses: actions/download-artifact@v4.1.7
```

2. Upgrade the version of `actions/upload-artifact` from v2 to v4.4.0

```diff
      - name: Create artifact
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v4.4.0
```

3. Sanitize the name of the artifact (only if the artifact name may contain the forbidden characters `" : < > | * ? \r \n \ /`)

```yml
      - name: Sanitize artifact name
        id: sanitize
        # This step removes special characters from the artifact name to ensure compatibility with upload-artifact
        # Characters removed: " : < > | * ? \r \n \ /
        # Spaces are replaced with underscores
        # This sanitization prevents errors in artifact creation and retrieval
        shell: pwsh
        run: |
          $originalName = "Cosserat_${{ steps.sofa.outputs.run_branch }}_for-SOFA-${{ steps.sofa.outputs.sofa_version }}_${{ runner.os }}"
          $artifact_name = $originalName -replace '[":;<>|*?\r\n\\/]', '' -replace ' ', '_'
          echo "artifact_name=$artifact_name" >> $env:GITHUB_OUTPUT

      - name: Create artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: ${{ steps.sanitize.outputs.artifact_name }}
          path: ${{ env.WORKSPACE_INSTALL_PATH }}

      - name: Install artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: ${{ steps.sanitize.outputs.artifact_name }}
          path: ${{ env.WORKSPACE_ARTIFACT_PATH }}
```

Examples where those changes have been applied:
- https://github.com/SofaDefrost/ModelOrderReduction/pull/140 the bot branch has been modified before the merge
- https://github.com/sofa-framework/SofaGLFW/pull/131 no PR from the security bot
- https://github.com/SofaDefrost/Cosserat/pull/129
- https://github.com/SofaDefrost/SoftRobots/pull/300
